name: Test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: CMake
      run: cmake -DBUILD_FLETCHER_AWS-SIM=ON .
    - name: Build
      run: make -j
